-- GENERATED BY scripts/generate-grants.mjs — DO NOT EDIT BY HAND.
-- Regenerate with: npm run grants:generate
--
-- One role per actor. A role holds exactly the privileges its manifests justify,
-- and nothing else: every run revokes the full set before granting, so a table
-- removed from a manifest loses its grant.

-- ------------------------------------------------------------------------
-- job: tenant-status-review
--   declared by manifests/jobs/tenant-status-review.yaml
--   connection string env var: DATABASE_URL_JOB_TENANT_STATUS_REVIEW
-- ------------------------------------------------------------------------
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'job_tenant_status_review') then
    create role "job_tenant_status_review" nologin;
  end if;
end $$;

revoke all on all tables in schema "public" from "job_tenant_status_review";
grant usage on schema "public" to "job_tenant_status_review";
revoke all on all tables in schema "audit" from "job_tenant_status_review";
grant usage on schema "audit" to "job_tenant_status_review";
revoke all on all tables in schema "traceable" from "job_tenant_status_review";
grant usage on schema "traceable" to "job_tenant_status_review";
grant execute on function audit.set_context(text, text, text, text) to "job_tenant_status_review";

-- llm_model_prices: run history, granted to every job
grant SELECT on "traceable"."llm_model_prices" to "job_tenant_status_review";
-- run_steps: run history, granted to every job
grant SELECT, INSERT, UPDATE on "traceable"."run_steps" to "job_tenant_status_review";
grant usage, select on all sequences in schema "traceable" to "job_tenant_status_review";
-- runs: run history, granted to every job
grant SELECT, INSERT, UPDATE on "traceable"."runs" to "job_tenant_status_review";
grant usage, select on all sequences in schema "traceable" to "job_tenant_status_review";
-- tenant_status_history: manifests/jobs/tenant-status-review.yaml
grant SELECT, INSERT, UPDATE, DELETE on "public"."tenant_status_history" to "job_tenant_status_review";
grant usage, select on all sequences in schema "public" to "job_tenant_status_review";
-- tenants: manifests/jobs/tenant-status-review.yaml
grant SELECT, INSERT, UPDATE, DELETE on "public"."tenants" to "job_tenant_status_review";
grant usage, select on all sequences in schema "public" to "job_tenant_status_review";

-- must_not_touch: these revokes are the enforcement, not a comment.
-- users: forbidden by manifests/jobs/tenant-status-review.yaml
revoke all on "public"."users" from "job_tenant_status_review";

-- ------------------------------------------------------------------------
-- service: devops
--   declared by manifests/apis/devops-apis.yaml
--   declared by manifests/apis/devops-audit.yaml
--   declared by manifests/apis/devops-data.yaml
--   declared by manifests/apis/devops-drift.yaml
--   declared by manifests/apis/devops-home.yaml
--   declared by manifests/apis/devops-jobs.yaml
--   declared by manifests/apis/devops-runs.yaml
--   connection string env var: DATABASE_URL_SVC_DEVOPS
-- ------------------------------------------------------------------------
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'svc_devops') then
    create role "svc_devops" nologin;
  end if;
end $$;

revoke all on all tables in schema "public" from "svc_devops";
grant usage on schema "public" to "svc_devops";
revoke all on all tables in schema "audit" from "svc_devops";
grant usage on schema "audit" to "svc_devops";
revoke all on all tables in schema "traceable" from "svc_devops";
grant usage on schema "traceable" to "svc_devops";
grant execute on function audit.set_context(text, text, text, text) to "svc_devops";

-- audit_log: manifests/apis/devops-audit.yaml
grant SELECT on "audit"."audit_log" to "svc_devops";
-- run_steps: manifests/apis/devops-runs.yaml
grant SELECT on "traceable"."run_steps" to "svc_devops";
-- runs: manifests/apis/devops-jobs.yaml, manifests/apis/devops-runs.yaml
grant SELECT on "traceable"."runs" to "svc_devops";
-- tenant_status_history: manifests/apis/devops-data.yaml
grant SELECT on "public"."tenant_status_history" to "svc_devops";
-- tenants: manifests/apis/devops-data.yaml
grant SELECT on "public"."tenants" to "svc_devops";

-- must_not_touch: these revokes are the enforcement, not a comment.
-- users: forbidden by manifests/apis/devops-apis.yaml, manifests/apis/devops-audit.yaml, manifests/apis/devops-data.yaml, manifests/apis/devops-drift.yaml, manifests/apis/devops-home.yaml, manifests/apis/devops-jobs.yaml, manifests/apis/devops-runs.yaml
revoke all on "public"."users" from "svc_devops";

-- ------------------------------------------------------------------------
-- service: health
--   declared by manifests/apis/health-check.yaml
--   connection string env var: DATABASE_URL_SVC_HEALTH
-- ------------------------------------------------------------------------
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'svc_health') then
    create role "svc_health" nologin;
  end if;
end $$;

revoke all on all tables in schema "public" from "svc_health";
grant usage on schema "public" to "svc_health";
revoke all on all tables in schema "audit" from "svc_health";
grant usage on schema "audit" to "svc_health";
revoke all on all tables in schema "traceable" from "svc_health";
grant usage on schema "traceable" to "svc_health";
grant execute on function audit.set_context(text, text, text, text) to "svc_health";

-- no table grants: this actor's manifests declare no reads or writes

-- must_not_touch: these revokes are the enforcement, not a comment.
-- tenant_status_history: forbidden by manifests/apis/health-check.yaml
revoke all on "public"."tenant_status_history" from "svc_health";
-- tenants: forbidden by manifests/apis/health-check.yaml
revoke all on "public"."tenants" from "svc_health";
-- users: forbidden by manifests/apis/health-check.yaml
revoke all on "public"."users" from "svc_health";

-- ------------------------------------------------------------------------
-- service: tenant-admin
--   declared by manifests/apis/tenant-get.yaml
--   declared by manifests/apis/tenant-list.yaml
--   declared by manifests/apis/tenant-status-update.yaml
--   connection string env var: DATABASE_URL_SVC_TENANT_ADMIN
-- ------------------------------------------------------------------------
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'svc_tenant_admin') then
    create role "svc_tenant_admin" nologin;
  end if;
end $$;

revoke all on all tables in schema "public" from "svc_tenant_admin";
grant usage on schema "public" to "svc_tenant_admin";
revoke all on all tables in schema "audit" from "svc_tenant_admin";
grant usage on schema "audit" to "svc_tenant_admin";
revoke all on all tables in schema "traceable" from "svc_tenant_admin";
grant usage on schema "traceable" to "svc_tenant_admin";
grant execute on function audit.set_context(text, text, text, text) to "svc_tenant_admin";

-- tenant_status_history: manifests/apis/tenant-get.yaml
grant SELECT on "public"."tenant_status_history" to "svc_tenant_admin";
-- tenants: manifests/apis/tenant-get.yaml, manifests/apis/tenant-list.yaml, manifests/apis/tenant-status-update.yaml
grant SELECT on "public"."tenants" to "svc_tenant_admin";

-- must_not_touch: these revokes are the enforcement, not a comment.
-- users: forbidden by manifests/apis/tenant-get.yaml, manifests/apis/tenant-list.yaml, manifests/apis/tenant-status-update.yaml
revoke all on "public"."users" from "svc_tenant_admin";

