#!/usr/bin/env node
// traceable-backend: generate the roles-and-grants migration FROM the manifests.
//
// Grants are never hand-written. This is what keeps rule 3 ("not touched" is
// enforced, not claimed) true: the set of privileges a role holds is a pure
// function of the manifests, regenerated in full every time, so removing a table
// from data.reads produces a REVOKE rather than a stale grant nobody notices.
//
// Usage:
//   node scripts/generate-grants.mjs [projectRoot]            write the migration
//   node scripts/generate-grants.mjs [projectRoot] --stdout   print it instead

import { writeFileSync, mkdirSync, existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import {
  loadConfig, loadManifests, crossReference, actorsFrom, grantPlan, printFindings,
} from './lib/core.mjs';

const args = process.argv.slice(2);
const toStdout = args.includes('--stdout');
const projectRoot = resolve(args.find((a) => !a.startsWith('--')) ?? process.cwd());

const config = loadConfig(projectRoot);
const manifests = loadManifests(config);
const findings = [...manifests.findings, ...(manifests.findings.length ? [] : crossReference(manifests, config))];

if (findings.length) {
  console.error('Refusing to generate grants from invalid manifests.\n');
  printFindings(findings, 0);
  process.exit(1);
}

const actors = actorsFrom(manifests);
const tables = new Map(manifests.tables.map((t) => [t.metadata.name, t.spec.schema ?? 'public']));
// Every schema the manifests mention. Revoking only in public would leave stale
// grants in the audit and traceable schemas, where the read-only DevOps role lives.
const allSchemas = [...new Set(['public', 'audit', 'traceable', ...tables.values()])];

const q = (s) => `"${s.replace(/"/g, '""')}"`;
const lines = [];

lines.push('-- GENERATED BY scripts/generate-grants.mjs — DO NOT EDIT BY HAND.');
lines.push('-- Regenerate with: npm run grants:generate');
lines.push('--');
lines.push('-- One role per actor. A role holds exactly the privileges its manifests justify,');
lines.push('-- and nothing else: every run revokes the full set before granting, so a table');
lines.push('-- removed from a manifest loses its grant.');
lines.push('');

for (const actor of actors) {
  const plan = grantPlan(actor);
  const forbidden = [...actor.mustNotTouch.keys()].sort();

  lines.push('-- ' + '-'.repeat(72));
  lines.push(`-- ${actor.kind}: ${actor.name}`);
  for (const m of actor.members) lines.push(`--   declared by ${m.file}`);
  lines.push(`--   connection string env var: ${actor.envVar}`);
  lines.push('-- ' + '-'.repeat(72));

  // Idempotent role creation. NOLOGIN by default: the deployment sets a password
  // out of band, so no credential is ever written into a committed migration.
  lines.push(`do $$ begin`);
  lines.push(`  if not exists (select 1 from pg_roles where rolname = '${actor.role}') then`);
  lines.push(`    create role ${q(actor.role)} nologin;`);
  lines.push(`  end if;`);
  lines.push(`end $$;`);
  lines.push('');

  for (const schema of allSchemas) {
    lines.push(`revoke all on all tables in schema ${q(schema)} from ${q(actor.role)};`);
    lines.push(`grant usage on schema ${q(schema)} to ${q(actor.role)};`);
  }
  lines.push(`grant execute on function audit.set_context(text, text, text, text) to ${q(actor.role)};`);
  lines.push('');

  if (plan.size === 0) {
    lines.push(`-- no table grants: this actor's manifests declare no reads or writes`);
  }
  for (const [table, privs] of [...plan.entries()].sort()) {
    const schema = tables.get(table) ?? 'public';
    const ordered = ['SELECT', 'INSERT', 'UPDATE', 'DELETE'].filter((p) => privs.has(p));
    const why = [
      ...(actor.reads.get(table) ?? []),
      ...(actor.writes.get(table) ?? []),
    ];
    lines.push(`-- ${table}: ${[...new Set(why)].join(', ') || 'run history, granted to every job'}`);
    lines.push(`grant ${ordered.join(', ')} on ${q(schema)}.${q(table)} to ${q(actor.role)};`);
    if (ordered.includes('INSERT')) {
      lines.push(`grant usage, select on all sequences in schema ${q(schema)} to ${q(actor.role)};`);
    }
  }
  lines.push('');

  if (forbidden.length) {
    lines.push(`-- must_not_touch: these revokes are the enforcement, not a comment.`);
    for (const table of forbidden) {
      const schema = tables.get(table) ?? 'public';
      const why = actor.mustNotTouch.get(table).join(', ');
      lines.push(`-- ${table}: forbidden by ${why}`);
      lines.push(`revoke all on ${q(schema)}.${q(table)} from ${q(actor.role)};`);
    }
    lines.push('');
  }
}

const sql = lines.join('\n') + '\n';

if (toStdout) {
  process.stdout.write(sql);
  process.exit(0);
}

// Reuse the existing generated migration directory so regeneration produces a
// diff rather than a new migration every run — that is what lets CI check the
// committed file is not stale.
const migrationsDir = join(projectRoot, config.grantsMigrationDir);
mkdirSync(migrationsDir, { recursive: true });
const existing = readdirSync(migrationsDir).filter((d) => d.endsWith('_traceable_grants')).sort();
const dirName = existing.length
  ? existing[existing.length - 1]
  : `${new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14)}_traceable_grants`;
const target = join(migrationsDir, dirName);
mkdirSync(target, { recursive: true });
const file = join(target, 'migration.sql');

const before = existsSync(file) ? readFileSync(file, 'utf8') : null;
writeFileSync(file, sql);

const rel = file.slice(projectRoot.length + 1);
console.log(
  before === sql
    ? `OK  grants unchanged (${actors.length} roles) — ${rel}`
    : `WROTE  ${rel} — ${actors.length} roles: ${actors.map((a) => a.role).join(', ')}`
);
